name: Question or Help Request
description: Ask a question or request help with using the project
title: '[Question]: '
labels: ['question', 'help wanted']
assignees:
  -  # Assign yourself or leave empty
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Please provide as much detail as possible so we can help you effectively.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: question-description
    attributes:
      label: What is your question or what help do you need?
      description: Clearly describe your question, the problem you're trying to solve, or the help you're seeking.
      placeholder: Describe your question or problem here...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context (optional)
      description: Add any other context about the problem here, such as what you've already tried, code snippets, or error messages.
      render: markdown
    validations:
      required: false
